apply plugin: 'org.jetbrains.kotlin.multiplatform'

kotlin {
  [
    iosArm64(),
    iosX64(),
    iosSimulatorArm64(),
  ].each { iosTarget ->
    iosTarget.binaries.framework {
      baseName = 'EmojiSearchKt'
    }
  }

  sourceSets {
    commonMain {
      dependencies {
        implementation project(":schema:protocol-host")

        implementation project(":launcher")
        implementation project(":presenter-treehouse")
        implementation project(":schema:protocol-host")
        implementation libs.redwood.layout.uiview
        implementation libs.redwood.lazylayout.uiview
      }
    }
  }
}
