apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'app.cash.redwood.generator.testing'

archivesBaseName = 'schema-testing'

kotlin {
  iosArm64()
  iosX64()
  iosSimulatorArm64()

  js {
    browser()
  }

  jvm()

  sourceSets {
    commonMain {
      dependencies {
        api libs.redwood.layout.widget
        api libs.redwood.layout.testing
        api libs.redwood.lazylayout.widget
        api libs.redwood.lazylayout.testing
        api project(":values")
        api project(":schema:widget")
      }
    }
  }
}

redwoodSchema {
  source = project(":schema")
  type = 'com.example.redwood.emojisearch.EmojiSearch'
}
